apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: game-platform

bases:
  - ../../base

resources:
  - ../../../helm/charts/game-platform/templates/namespace.yaml
  - ../../../helm/charts/game-platform/templates/nginx-config.yaml
  - ../../../helm/charts/game-platform/templates/infrastructure.yaml
  - ../../../helm/charts/game-platform/templates/monitoring.yaml
