apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-service-config
  namespace: game-platform
  labels:
    app: auth-service
data:
  COUCHBASE_HOST: {{ .Values.couchbase.host }}
  COUCHBASE_USER: {{ .Values.couchbase.user }}
  JWT_EXPIRY_HOURS: {{ .Values.jwt.expiryHours | quote }}