apiVersion: v1
kind: Secret
metadata:
  name: auth-service-secrets
  namespace: game-platform
  labels:
    app: auth-service
type: Opaque
stringData:
  jwt-secret: "{{ .Values.jwt.secret | default (randAlphaNum 32) }}"
  couchbase-password: {{ .Values.couchbase.password }}