apiVersion: v1
kind: Secret
metadata:
  name: couchbase-credentials
  namespace: infra
  labels:
    app: couchbase
type: Opaque
stringData:
  username: {{ .Values.auth.username | quote }}
  password: {{ .Values.auth.password | quote }}
