apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: notification-service
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/thorOdinson16/multiplayer-infra.git
    targetRevision: HEAD
    path: helm/notification-service
  destination:
    server: https://kubernetes.default.svc
    namespace: game-platform
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
