apiVersion: v1
kind: Secret
metadata:
  name: minio-credentials
  namespace: infra
  labels:
    app: minio
type: Opaque
stringData:
  username: {{ .Values.auth.username }}
  password: {{ .Values.auth.password }}