apiVersion: v1
kind: Service
metadata:
  name: minio
  namespace: {{ .Release.Namespace }}
  labels:
    app: minio
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: api
      port: {{ .Values.service.apiPort }}
      targetPort: {{ .Values.service.apiPort }}
    - name: console
      port: {{ .Values.service.consolePort }}
      targetPort: {{ .Values.service.consolePort }}
  selector:
    app: minio
