import os
import json
import time
import re
import signal
import subprocess
import threading
import logging
import etcd3
from fastapi import FastAPI

app = FastAPI(title="etcd-watcher-service")
logger = logging.getLogger("etcd-watcher")

ETCD_HOST = os.environ.get("ETCD_HOST", "etcd")
ETCD_PORT = int(os.environ.get("ETCD_PORT", "2379"))
NGINX_CONF_DIR = os.environ.get("NGINX_CONF_DIR", "/etc/nginx/conf.d")
UPSTREAM_TEMPLATE = os.environ.get("UPSTREAM_TEMPLATE", "game-room-upstream.conf")

DEBOUNCE_SECONDS = 2

logger.info(f"etcd-watcher starting: etcd={ETCD_HOST}:{ETCD_PORT}, conf_dir={NGINX_CONF_DIR}")

_debounce_timer = None
_debounce_lock = threading.Lock()
_pending_upstreams = {}


def get_etcd():
    return etcd3.client(host=ETCD_HOST, port=ETCD_PORT)


def generate_upstream_config(upstreams):
    lines = ["# Auto-generated by etcd-watcher", f"# Updated: {time.ctime()}", ""]
    for match_id, address in sorted(upstreams.items()):
        safe_name = f"game_room_{re.sub(r'[^a-zA-Z0-9_]', '_', match_id)}"
        lines.append(f"upstream {safe_name} {{")
        lines.append(f"    server {address};")
        lines.append("}")
        lines.append("")
    lines.append("map $arg_match_id $game_room_upstream {")
    lines.append("    default game_room;")
    for match_id, address in sorted(upstreams.items()):
        safe_name = f"game_room_{re.sub(r'[^a-zA-Z0-9_]', '_', match_id)}"
        escaped_id = re.escape(match_id)
        lines.append(f"    ~{escaped_id}$ {safe_name};")
    lines.append("}")
    return "\n".join(lines)


def write_upstream_config(upstreams):
    conf_path = os.path.join(NGINX_CONF_DIR, UPSTREAM_TEMPLATE)
    content = generate_upstream_config(upstreams)
    tmp_path = conf_path + ".tmp"
    try:
        with open(tmp_path, "w") as f:
            f.write(content)
        os.rename(tmp_path, conf_path)
        logger.info(f"Wrote upstream config: {len(upstreams)} matches")
        subprocess.run(["nginx", "-s", "reload"], capture_output=True, timeout=5)
        logger.info("NGINX reloaded")
    except Exception as e:
        logger.error(f"Failed to update NGINX config: {e}")


def load_current_upstreams():
    client = get_etcd()
    upstreams = {}
    try:
        for value, metadata in client.get_prefix("/match/", keys_only=False):
            key = metadata.key.decode()
            if key.endswith("/leader-address") and value:
                match_id = key.split("/")[2]
                upstreams[match_id] = value.decode()
    except Exception as e:
        logger.error(f"Failed to load upstreams: {e}")
    return upstreams


def _do_write():
    global _debounce_timer
    with _debounce_lock:
        upstreams = dict(_pending_upstreams)
        _pending_upstreams.clear()
        _debounce_timer = None
    if upstreams:
        write_upstream_config(upstreams)


def _schedule_debounced_write(upstreams):
    global _debounce_timer
    with _debounce_lock:
        _pending_upstreams.update(upstreams)
        if _debounce_timer is None:
            _debounce_timer = threading.Timer(DEBOUNCE_SECONDS, _do_write)
            _debounce_timer.daemon = True
            _debounce_timer.start()


def watch_etcd():
    client = get_etcd()
    last_upstreams = load_current_upstreams()
    if last_upstreams:
        _schedule_debounced_write(last_upstreams)
    watch_prefix = "/match/"
    while True:
        try:
            events = client.watch_prefix(watch_prefix, timeout=60)
            for event in events:
                pass
            upstreams = load_current_upstreams()
            if upstreams != last_upstreams:
                last_upstreams = upstreams
                _schedule_debounced_write(upstreams)
        except Exception as e:
            logger.error(f"Watch error: {e}, reconnecting...")
            time.sleep(2)


@app.on_event("startup")
async def startup():
    import asyncio
    loop = asyncio.get_event_loop()
    loop.run_in_executor(None, watch_etcd)


@app.get("/health")
async def health():
    return {"status": "ok"}


@app.get("/ready")
async def ready():
    return {"status": "ready"}


@app.get("/upstreams")
async def get_upstreams():
    return load_current_upstreams()


if __name__ == "__main__":
    import uvicorn
    port = int(os.environ.get("PORT", 8000))
    uvicorn.run(app, host="0.0.0.0", port=port)
