apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: infra
  labels:
    app: kafka
spec:
  type: {{ .Values.service.type }}
  clusterIP: None
  ports:
    - name: internal
      port: {{ .Values.service.internalPort }}
      targetPort: {{ .Values.service.internalPort }}
      protocol: TCP
    - name: controller
      port: {{ .Values.service.controllerPort }}
      targetPort: {{ .Values.service.controllerPort }}
      protocol: TCP
  selector:
    app: kafka