replicaCount: 1

image:
  repository: redis
  tag: "7.4-alpine"
  pullPolicy: IfNotPresent

resources:
  requests:
    memory: "128Mi"
    cpu: "100m"
  limits:
    memory: "512Mi"
    cpu: "500m"

service:
  port: 6379
  type: ClusterIP