apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq-config
  namespace: {{ .Release.Namespace }}
  labels:
    app: rabbitmq
data:
  10-defaults.conf: |
    loopback_users.guest = false
    management.tcp.port = 15672
