apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-credentials
  namespace: infra
  labels:
    app: rabbitmq
type: Opaque
stringData:
  username: {{ .Values.auth.username }}
  password: {{ .Values.auth.password }}