apiVersion: v1
kind: ConfigMap
metadata:
  name: game-room-server-config
  namespace: game-platform
  labels:
    app: game-room-server
data:
  KAFKA_BROKERS: {{ .Values.kafka.brokers }}
  REDIS_ADDR: {{ .Values.redis.addr }}
  COUCHBASE_HOST: {{ .Values.couchbase.host }}
  COUCHBASE_USER: {{ .Values.couchbase.user }}
  MAX_PLAYERS: {{ .Values.maxPlayers | quote }}
  TICK_RATE: {{ .Values.tickRate | quote }}
  MATCH_ID: {{ .Values.matchId | quote }}
  OTEL_EXPORTER_OTLP_ENDPOINT: {{ .Values.otel.endpoint | quote }}
  RAFT_CLUSTER_SIZE: {{ .Values.replicaCount | quote }}
  RAFT_SERVICE: "game-room-server-headless"
  RAFT_NAMESPACE: "game-platform"
  ETCD_ENDPOINTS: "etcd.infra.svc.cluster.local:2379"
