{{- if and (eq (int .Values.replicaCount) 1) .Values.persistence.createStandalonePvc }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: game-room-server-data
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  storageClassName: {{ .Values.persistence.storageClass }}
{{- end }}
