apiVersion: v1
kind: Service
metadata:
  name: game-room-server-headless
  namespace: game-platform
  labels:
    app: game-room-server
spec:
  clusterIP: None
  ports:
    - name: http
      port: {{ .Values.service.httpPort }}
    - name: raft
      port: {{ .Values.service.raftPort }}
  selector:
    app: game-room-server