apiVersion: v1
kind: ConfigMap
metadata:
  name: replay-service-config
  namespace: game-platform
  labels:
    app: replay-service
data:
  KAFKA_BROKERS: {{ .Values.kafka.brokers }}
  COUCHBASE_HOST: {{ .Values.couchbase.host }}
  COUCHBASE_USER: {{ .Values.couchbase.user }}
  MINIO_ENDPOINT: {{ .Values.minio.endpoint }}
  MINIO_USER: {{ .Values.minio.user }}