apiVersion: v1
kind: ConfigMap
metadata:
  name: replay-service-config
  namespace: {{ .Release.Namespace }}
  labels:
    app: replay-service
data:
  KAFKA_BROKERS: {{ .Values.kafka.brokers }}
  COUCHBASE_HOST: {{ .Values.couchbase.host }}
  COUCHBASE_USER: {{ .Values.couchbase.user }}
  MINIO_ENDPOINT: {{ .Values.minio.endpoint }}
  MINIO_USER: {{ .Values.minio.user }}
  OTEL_EXPORTER_OTLP_ENDPOINT: {{ .Values.otel.endpoint | quote }}
